// =============================================================================
// Gamebuino Classic -> Vircon32 port - master build file
// =============================================================================
// Vircon32 has no linker: a program is exactly one translation unit, built
// from a single .c file passed to compile.exe. This file is that single
// entry point: it #includes every module in dependency order, then
// portVircon32.c last (which defines the machine-dependent hooks and
// main()). Same layout as the sibling tinyjoypad_vircon32 project's own
// main.c.
//
// Build: see Make.bat/Make.sh at the project root for the exact commands.
// =============================================================================

#include "misc.h"
#include "math.h"

#include "avrCompat.h"
#include "machineDependent.h"
#include "menu.h"
#include "menu.c"

#include "gamebuinoShim.h"
#include "gamebuinoShim.c"

#include "eepromShim.h"
#include "eepromShim.c"

#include "games/gamePong.c"
#include "games/gameAgaruino.c"
#include "games/gameShufflepuck.c"
#include "games/gameTaquin.c"
#include "games/gameCrazyCar.c"
#include "games/gameMaze.c"
#include "games/gameSimonbuino.c"
#include "games/gameConduit.c"
#include "games/gameFlappyBirdo.c"
#include "games/gameParachute.c"
#include "games/gameSnakeClassic.c"
#include "games/gameSnakeAbc.c"
#include "games/gameFiremen.c"
#include "games/gameCatcher.c"
#include "games/gameUfoRace.c"
#include "games/gameMinesweeper.c"
#include "games/gameKillrace.c"
#include "games/gameBlockdude.c"
#include "games/gameLander.c"
#include "games/gamePunkt.c"
#include "games/gameInvaders.c"
#include "games/gameAsterocks.c"
#include "games/gameGruniozerca.c"
#include "games/gameVideoPoker.c"
#include "games/gameBlobAttack.c"
#include "games/gameSmash.c"
#include "games/game2048.c"
#include "games/gameArmageddon.c"
#include "games/gameSkibuino.c"
#include "games/gameHexagon.c"
#include "games/gameJezzball.c"
#include "games/gameShipwrek.c"
#include "games/gamePaqman.c"
#include "games/gameBlocksBuino.c"
#include "games/gameWhg.c"
#include "games/gameCrazyTown.c"
#include "games/gameCopter.c"
#include "games/gameZombiEscape.c"
#include "games/gameGlaciGlaca.c"
#include "games/gameDescent.c"
#include "games/gameCastleDefence.c"
#include "games/gameDigger.c"
#include "games/gameSuperSpaceShooter.c"
#include "games/gameTetrino.c"
#include "games/gameArtillery.c"
#include "games/gameCrabator.c"
#include "games/gameBRally.c"
#include "games/gameMaruino.c"
#include "games/gameSuperCrateBuino.c"
#include "games/gameFirebuino.c"
#include "games/gameStarships101.c"
#include "games/gameSolitaire.c"
#include "games/gameA2K.c"
#include "games/gameSokobuino.c"
#include "games/gameDeathMaze.c"
#include "games/gameAsteroidRipper.c"
#include "games/gameBangBang.c"
#include "games/gameBreakoutRipper.c"
#include "games/gameLightsOutAD.c"
#include "games/gameThunderShoot.c"
#include "games/gameBub.c"
#include "games/gameTrexQuest.c"
#include "games/gameShootBuino.c"
#include "games/gameSenet.c"
#include "games/gameBomber.c"
#include "games/gameStickFighter.c"
#include "games/gameTron.c"
#include "games/gameSpinSpinSpinbuino.c"
#include "games/gameSnake5110.c"
#include "games/gamePongLocalMultiplayer.c"
#include "games/gameSavePrincesse.c"
#include "games/gameMotoCross.c"
#include "games/gameNoNamePlatformGame.c"
#include "games/gameStijnPong.c"
#include "games/gameStijnSnake.c"
#include "games/gameMasterKebab.c"
#include "games/gameAimbuino.c"
#include "games/gameRalph.c"
#include "games/gameFootlol.c"
#include "games/gameMyRpg.c"
#include "games/gamePong2017.c"
#include "games/gameDarkShmup.c"
#include "games/gamePinball.c"
#include "games/gameRobot.c"
#include "games/gameElventure.c"
#include "games/gameStarHonor.c"
#include "games/gamePetitMonstre.c"
#include "games/gameUnderTheTower.c"
#include "games/gameBigBlackBox.c"
#include "games/gameCruiser.c"
#include "games/gameCopterStrike.c"
#include "games/gameXonix.c"
#include "games/gameAnother2048.c"
#include "games/gameDarkTower.c"
#include "games/gameGemgem.c"
#include "games/gameCommunityRpg.c"
#include "games/gameFifteen.c"
#include "games/gameMoleControl.c"
#include "games/gameAerialAssault.c"
#include "games/gameRsg.c"
#include "games/gameDiscovery.c"
#include "games/gameBomberman.c"
#include "games/gameBricks.c"
#include "games/gameWolfenduino.c"
#include "games/gameGuessANumber.c"
#include "games/gameWalbloks.c"
#include "games/gameSnakeSigma.c"
#include "games/gameCopterAnny.c"
#include "games/gameSienaTown.c"
#include "games/gameSuperCrateBuinoStone.c"
#include "games/gameSoundTest.c"

#include "menuGameList.c"

// ---- Vircon32-specific machine-dependent layer + main() ----
#include "portVircon32.c"
