// =============================================================================
// Vircon32-specific machine-dependent layer + main()
// =============================================================================
// Implements every md_* primitive declared in machineDependent.h, on top of
// the real video.h/input.h/audio.h/time.h. Also owns the top-level menu <->
// game dispatch loop.
//
// Modeled directly on the sibling tinyjoypad_vircon32 project's own
// portVircon32.c - same overall architecture (a 256-tile pre-baked column
// atlas standing in for a CPU-writable framebuffer). The thumbnail atlas,
// quit-confirmation dialog, pixel-grid overlay, global mute toggle, and
// memory-card/EEPROM persistence below are all direct ports of that
// project's own equivalents, added once this project had more than a single
// game's worth of reason to want them.
// =============================================================================

#include "machineDependent.h"
#include "gamebuinoShim.h"
#include "menu.h"
#include "menuGameList.h"

#include "video.h"
#include "input.h"
#include "audio.h"
#include "time.h"
#include "memcard.h"
#include "../libs/PlayNote/playnote.h"

// -----------------------------------------------------------------------------
//   PRESENTATION LAYOUT
// -----------------------------------------------------------------------------

// 84 LCD px * 7 = 588, 48 * 7 = 336 - centered in the 640x360 screen with a
// 26px bar left/right and an 12px bar top/bottom.
#define TILE_SCALE   7
#define ATLAS_GRID   16
#define TILE_W       TILE_SCALE
#define TILE_H       ( 8 * TILE_SCALE )
#define ORIGIN_X     26
#define ORIGIN_Y     12

#define COLUMNS_TEXTURE_ID 0
// libs/PlayNote/sounds/wt_square.wav - a real, hard-edged 50%-duty square
// wave (tools/gen_square_wavetable.py), matching real Gamebuino Classic
// hardware's own default instrument exactly: real Sound.cpp drives its
// piezo speaker with a genuine 2-level PWM square wave (toggling
// _chanState high/low every half-period in updateOutput()/generateOutput() -
// no duty-cycle control of its own, amplitude is the only thing a real
// instrument step varies), not PlayNote's own generic sawtooth sample.
#define WAVETABLE_SOUND_ID 0
// See the sibling tinyjoypad_vircon32 project's own portVircon32.c for the
// full story on why this needs to be short enough to keep the SPU's own
// hardware speed-register clamp (0-128) from silently ceiling every note
// above ~2.7kHz to the same pitch - 256 samples raises that ceiling to
// ~22kHz, comfortably covering anything a Gamebuino Classic game's own
// Sound()-equivalent note range is likely to ask for.
#define WAVETABLE_PERIOD_SAMPLES 256

// Menu game-select thumbnails: one real gameplay screenshot per game
// (assets/thumbnails.png, cropped/scaled from an actual Puppeteer capture of
// the game running, matching the sibling tinyjoypad_vircon32 project's own
// "built offline from actual play captures" discipline - not a mockup).
// Grew from a 4x1 grid (4 cells) to 4x3 (12) to 4x6 (1024x768, 24 cells)
// once the 10 games ported after SNAKE ABC each had a real capture ready -
// region ids assigned in addGames()'s own registration order (NOT the
// menu's own alphabetical display order - see menu.c's own selection-
// sort). Same THUMBNAIL_W/H/grid-of-regions design as the sibling
// tinyjoypad_vircon32 project's own thumbnails.png.
//
// Batch 3 (20 more games) needed 20 more cells, but simply growing this
// same texture taller (to 4x11, 1024x1408) was tried first and rejected:
// `packrom` genuinely refused it ("texture size is larger than allowed by
// Vircon32 GPU") - confirmed empirically, not assumed. Real Vircon32 GPU
// textures are capped at 1024x1024 - grown this texture up to exactly that
// ceiling instead (4x8, 1024x1024, 32 cells - region ids 0-31, holding
// registration indices 0-31), and added a second, small
// THUMBNAILS2_TEXTURE_ID (below) for the remaining registration indices
// (32 and up) rather than trying to squeeze everything into one texture -
// the second-texture approach this file's own earlier comment had already
// anticipated, just triggered by hitting the real 1024x1024 ceiling instead
// of running out of an arbitrarily-sized single texture.
#define THUMBNAILS_TEXTURE_ID 1
#define THUMBNAIL_W MD_THUMBNAIL_WIDTH
#define THUMBNAIL_H MD_THUMBNAIL_HEIGHT
#define THUMBNAIL_GRID_COLS 4
#define THUMBNAIL_GRID_ROWS 8
#define THUMBNAIL_SPLIT 32

// Pixel-grid overlay (see drawPixelGridOverlay() below) - one pre-baked
// 588x336 texture (assets/pixelgrid.png, generated by tools/gen_pixelgrid.py
// - a transparent background with opaque black 1px lines at every
// TILE_SCALE-pixel boundary in both directions) instead of drawing 132
// individual md_drawSolidRect() lines by hand. Direct port of the sibling
// tinyjoypad_vircon32 project's own identical design - see that project's
// own portVircon32.c/CLAUDE.md for the full rationale (relies on
// blending_alpha, the GPU's own default mode, so only the opaque grid-line
// pixels actually affect the screen). Texture id 2.
#define PIXELGRID_TEXTURE_ID 2

// Second thumbnail atlas - see THUMBNAILS_TEXTURE_ID's own comment above
// for why this exists (the first texture is already at the real, confirmed
// 1024x1024 Vircon32 GPU texture size ceiling). Holds registration indices
// THUMBNAIL_SPLIT..THUMBNAIL_SPLIT2-1. Appended after PIXELGRID_TEXTURE_ID
// (id 3) rather than inserted right after THUMBNAILS_TEXTURE_ID, matching
// this project's own "append, don't insert" precedent for texture ids (see
// the sibling tinyjoypad_vircon32 project's own CLAUDE.md). Grown from 4x6
// (24 cells) to 4x8 (32 cells, 1024x1024) once batch-5 porting brought the
// real registered-game count to 64 (indices 32-63 - exactly 32 needed) -
// this texture is at the exact same real, confirmed 1024x1024 GPU ceiling
// the first texture already hit, with zero cells of headroom left.
#define THUMBNAILS2_TEXTURE_ID 3
#define THUMBNAIL2_GRID_COLS 4
#define THUMBNAIL2_GRID_ROWS 8
#define THUMBNAIL_SPLIT2 64

// Third thumbnail atlas, needed the moment the real registered-game count
// passed 64 (both earlier textures are already at the real 1024x1024 GPU
// ceiling with zero cells to spare) - holds registration indices
// THUMBNAIL_SPLIT2 and up. Appended after GRAYCOLUMNS_TEXTURE_ID (id 4)
// rather than inserted earlier, matching this project's own "append, don't
// insert" precedent for texture ids. Grown from 4x3 (12 cells, 1024x384) to
// 4x5 (20 cells, 1024x640) once the "port all staged tier 1 games" batch
// brought the real registered-game count to 79, then to 4x6 (24 cells,
// 1024x768) once the "port all tier 2 games" batch brought it to 84 (the
// previous 20-cell capacity was now exactly full, zero cells to spare) -
// the same "modest headroom past the real current total" reason as every
// earlier thumbnail-atlas growth in this project.
#define THUMBNAILS3_TEXTURE_ID 5
#define THUMBNAIL3_GRID_COLS 4
#define THUMBNAIL3_GRID_ROWS 6
#define THUMBNAIL_SPLIT3 88

// Fourth thumbnail atlas, needed the moment the real registered-game count
// passed 88 (the third texture's own 4x6/24-cell capacity, added during
// the Tier 2 batch, was by then exactly full - zero cells to spare) -
// holds registration indices THUMBNAIL_SPLIT3 and up. Appended after
// THUMBNAILS3_TEXTURE_ID (id 5) rather than inserted earlier, matching
// this project's own "append, don't insert" precedent for texture ids.
// Sized 4x6 (24 cells, 1024x768), covering registration indices 88..111 -
// still well under the real 1024x1024 Vircon32 GPU texture ceiling.
#define THUMBNAILS4_TEXTURE_ID 6
#define THUMBNAIL4_GRID_COLS 4
#define THUMBNAIL4_GRID_ROWS 6
#define THUMBNAIL_COUNT 111

// Same 256-tile-per-byte-value layout as COLUMNS_TEXTURE_ID above (see
// tools/gen_column_atlas_gray.py), but "lit" bits are a real opaque
// mid-gray and "off" bits are fully transparent - only ever selected by
// md_drawColumnGray() below, which gbRenderFrame() calls as a second,
// targeted pass whenever the runtime gbRealGrayColor toggle is on (see
// gamebuinoShim.h's own Configuration section). Appended after
// THUMBNAILS2_TEXTURE_ID, matching this project's own "append, don't
// insert" precedent for texture ids.
#define GRAYCOLUMNS_TEXTURE_ID 4

void md_initVideo()
{
    select_texture( COLUMNS_TEXTURE_ID );

    define_region_matrix
    (
        0,                              // first_id (region id == byte value)
        0, 0, TILE_W - 1, TILE_H - 1,   // first tile bounds
        0, 0,                           // hotspot at top-left
        ATLAS_GRID, ATLAS_GRID,         // 16x16 = 256 tiles
        0                               // no gap between tiles
    );

    select_texture( THUMBNAILS_TEXTURE_ID );

    define_region_matrix
    (
        0,                                          // first_id == game index
        0, 0, THUMBNAIL_W - 1, THUMBNAIL_H - 1,     // first tile bounds
        0, 0,                                       // hotspot at top-left
        THUMBNAIL_GRID_COLS, THUMBNAIL_GRID_ROWS,
        0
    );

    select_texture( PIXELGRID_TEXTURE_ID );
    select_region( 0 );
    define_region( 0, 0, LCD_WIDTH * TILE_SCALE - 1, LCD_HEIGHT * TILE_SCALE - 1, 0, 0 );

    select_texture( THUMBNAILS2_TEXTURE_ID );

    define_region_matrix
    (
        0,                                          // first_id == (game index - THUMBNAIL_SPLIT)
        0, 0, THUMBNAIL_W - 1, THUMBNAIL_H - 1,     // first tile bounds
        0, 0,                                       // hotspot at top-left
        THUMBNAIL2_GRID_COLS, THUMBNAIL2_GRID_ROWS,
        0
    );

    select_texture( THUMBNAILS3_TEXTURE_ID );

    define_region_matrix
    (
        0,                                          // first_id == (game index - THUMBNAIL_SPLIT2)
        0, 0, THUMBNAIL_W - 1, THUMBNAIL_H - 1,     // first tile bounds
        0, 0,                                       // hotspot at top-left
        THUMBNAIL3_GRID_COLS, THUMBNAIL3_GRID_ROWS,
        0
    );

    select_texture( THUMBNAILS4_TEXTURE_ID );

    define_region_matrix
    (
        0,                                          // first_id == (game index - THUMBNAIL_SPLIT3)
        0, 0, THUMBNAIL_W - 1, THUMBNAIL_H - 1,     // first tile bounds
        0, 0,                                       // hotspot at top-left
        THUMBNAIL4_GRID_COLS, THUMBNAIL4_GRID_ROWS,
        0
    );

    select_texture( GRAYCOLUMNS_TEXTURE_ID );

    define_region_matrix
    (
        0,                              // first_id (region id == byte value)
        0, 0, TILE_W - 1, TILE_H - 1,   // first tile bounds
        0, 0,                           // hotspot at top-left
        ATLAS_GRID, ATLAS_GRID,         // 16x16 = 256 tiles
        0                               // no gap between tiles
    );

    set_multiply_color( color_white );
}

int md_getThumbnailCount()
{
    return THUMBNAIL_COUNT;
}

void md_drawGameThumbnail( int gameIndex, int x, int y )
{
    if( gameIndex < 0 || gameIndex >= THUMBNAIL_COUNT )
      return;

    if( gameIndex < THUMBNAIL_SPLIT )
    {
        select_texture( THUMBNAILS_TEXTURE_ID );
        select_region( gameIndex );
    }
    else if( gameIndex < THUMBNAIL_SPLIT2 )
    {
        select_texture( THUMBNAILS2_TEXTURE_ID );
        select_region( gameIndex - THUMBNAIL_SPLIT );
    }
    else if( gameIndex < THUMBNAIL_SPLIT3 )
    {
        select_texture( THUMBNAILS3_TEXTURE_ID );
        select_region( gameIndex - THUMBNAIL_SPLIT2 );
    }
    else
    {
        select_texture( THUMBNAILS4_TEXTURE_ID );
        select_region( gameIndex - THUMBNAIL_SPLIT3 );
    }
    draw_region_at( x, y );
}

// Solid-color filled rectangle - reuses the columns atlas's own region 255
// (byte value 0xFF - all 8 pixels lit, a plain TILE_W x TILE_H solid white
// tile already loaded for md_drawColumn) rather than adding a whole new
// texture asset just for this: video.h has no rectangle-fill primitive of
// its own, only region blits, so the standard trick (same one the sibling
// tinyjoypad_vircon32 project's own md_drawSolidRect() already uses) is to
// tint a solid region via set_multiply_color() and stretch it to any size
// via set_drawing_scale()+draw_region_zoomed_at(). Used by the quit-
// confirmation dialog below (white outline, black interior) - restores the
// multiply color/scale afterward since every other draw call in this file
// (md_drawColumn, print_at) assumes the neutral white/1x state left by
// md_initVideo().
void md_drawSolidRect( int x, int y, int w, int h, int color )
{
    select_texture( COLUMNS_TEXTURE_ID );
    // Region 0, not 255: a region's own pixels are MODULATED by the multiply
    // color, so the base tile has to be white for `color` to come through.
    // Byte value 0 is the all-"off" tile, which on this reflective-LCD atlas
    // is solid white (tools/gen_column_atlas.py draws "off" as the light
    // background); byte value 255 is the all-"lit" tile and is solid BLACK,
    // which multiplied by anything stays black. This used to select 255, so
    // md_drawSolidRect() silently painted black whatever color it was asked
    // for - the quit dialog's own white outline was invisible for the same
    // reason.
    select_region( 0 );
    set_multiply_color( color );
    set_drawing_scale( (float)w / TILE_W, (float)h / TILE_H );
    draw_region_zoomed_at( x, y );
    set_multiply_color( color_white );
    set_drawing_scale( 1.0, 1.0 );
}

// Clears to WHITE, not black - a real Nokia 5110/PCD8544 LCD (unlike the
// sibling tinyjoypad_vircon32 project's own self-illuminating SSD1306
// OLED) has a naturally light background, with a "set" pixel drawn as dark
// ink on top of it (see tools/gen_column_atlas.py's own header comment for
// the full story - a real bug found via direct user report, "colors seem
// inverted", not the original design). md_drawColumn() below relies on
// this exact color matching its own "skip value==0" optimization: a
// value of 0 (all 8 pixels off) is only ever a safe no-op because the
// frame was already cleared to the SAME color those "off" pixels would
// have drawn anyway.
void md_beginFrame()
{
    clear_screen( color_white );
    select_texture( COLUMNS_TEXTURE_ID );
}

void md_drawColumn( int col, int page, int value )
{
    // Vircon32 ints are full 32-bit words with no implicit byte truncation -
    // see the sibling tinyjoypad_vircon32 project's own extensively-
    // documented history of bugs from assuming AVR's uint8_t narrowing still
    // applies. Masked once at this single choke point, matching that
    // project's own established fix.
    value &= 0xFF;

    // value 0 (all 8 pixels off) is a no-op - md_beginFrame()'s own
    // clear_screen(color_white) call already left every one of those
    // pixels showing the exact same white the column atlas's own value-0
    // tile would otherwise draw (see that function's own comment).
    if( value == 0 )
      return;

    select_region( value );
    draw_region_at( ORIGIN_X + col * TILE_SCALE, ORIGIN_Y + page * TILE_H );
}

// Only ever called by gbRenderFrame() when the runtime gbRealGrayColor
// toggle is on - see GRAYCOLUMNS_TEXTURE_ID's own comment above. Unlike
// md_drawColumn(), this draws on top of whatever's already on screen for
// this same (col,page) cell (real semi-transparent gray, not an opaque white
// background), so it must select its own distinct texture every call
// rather than relying on md_beginFrame()'s own COLUMNS_TEXTURE_ID
// selection to still be current.
void md_drawColumnGray( int col, int page, int value )
{
    value &= 0xFF;
    if( value == 0 )
      return;

    select_texture( GRAYCOLUMNS_TEXTURE_ID );
    select_region( value );
    draw_region_at( ORIGIN_X + col * TILE_SCALE, ORIGIN_Y + page * TILE_H );
}

void md_endFrame()
{
    end_frame();
}

// -----------------------------------------------------------------------------
//   INPUT
// -----------------------------------------------------------------------------

int md_inputLeftFrames()  { return gamepad_left();  }
int md_inputRightFrames() { return gamepad_right(); }
int md_inputUpFrames()    { return gamepad_up();    }
int md_inputDownFrames()  { return gamepad_down();  }

// See machineDependent.h's own comment on md_armInputAGate() - while the
// gate is active, reports "long since released" instead of the real raw
// reading, matching the sibling tinyjoypad_vircon32 project's own
// md_inputFireFrames() exactly.
bool inputAGateActive = false;

int md_inputAFrames()
{
    int raw = gamepad_button_a();

    if( inputAGateActive )
    {
        if( raw <= 0 )
          inputAGateActive = false;
        return -3600;
    }

    return raw;
}

bool md_inputLeft()  { return md_inputLeftFrames()  > 0; }
bool md_inputRight() { return md_inputRightFrames() > 0; }
bool md_inputUp()    { return md_inputUpFrames()    > 0; }
bool md_inputDown()  { return md_inputDownFrames()  > 0; }
bool md_inputA()     { return md_inputAFrames()     > 0; }
bool md_inputB()     { return gamepad_button_b() > 0; }
bool md_inputC()     { return gamepad_button_x() > 0; }
bool md_inputStart() { return gamepad_button_start() > 0; }

void md_armInputAGate()
{
    inputAGateActive = true;
}

// -----------------------------------------------------------------------------
//   AUDIO
// -----------------------------------------------------------------------------
// Same genuinely-multi-voice design as the sibling tinyjoypad_vircon32
// project's own md_playTone() - see that file's own header comment for the
// full rationale (PlayNote's own playnote_start() already picks a free SPU
// channel internally, so there's no need to manually track a single shared
// voice the way an original single-piezo-buzzer game's own Sound() call
// implicitly assumed).

#define AUDIO_MAX_VOICES 16
int[AUDIO_MAX_VOICES] audioStopAtFrame;

void md_initAudio()
{
    playnote_init( WAVETABLE_SOUND_ID, WAVETABLE_PERIOD_SAMPLES );
    int i;
    for( i = 0; i < AUDIO_MAX_VOICES; i++ )
      audioStopAtFrame[ i ] = -1;
}

void md_playTone( float freqHz, float durationSeconds )
{
    if( freqHz <= 0.0 )
      return;

    int channel = playnote_start( freqHz, 0.6 );
    if( channel < 0 )
      return;

    int durationFrames = (int)( durationSeconds * frames_per_second );
    if( durationFrames < 1 )
      durationFrames = 1;

    audioStopAtFrame[ channel ] = get_frame_counter() + durationFrames;
}

void md_stopTone()
{
    playnote_stop_all();
    int i;
    for( i = 0; i < AUDIO_MAX_VOICES; i++ )
      audioStopAtFrame[ i ] = -1;
}

void md_updateAudio()
{
    int i;
    for( i = 0; i < AUDIO_MAX_VOICES; i++ )
    {
        if( audioStopAtFrame[ i ] != -1 && get_frame_counter() >= audioStopAtFrame[ i ] )
        {
            playnote_stop( i );
            audioStopAtFrame[ i ] = -1;
        }
    }

    playnote_update();
}

// See machineDependent.h's own doc comment for the full rationale (a
// continuously-retunable voice, for gamebuinoShim.c's own tracker/pattern
// engine, distinct from the fixed-duration one-shot pool above).
int md_trackerVoiceStart( float freqHz, float volume )
{
    if( freqHz <= 0.0 )
      return -1;
    return playnote_start( freqHz, volume );
}

void md_trackerVoiceRetune( int channel, float freqHz, float volume )
{
    if( channel < 0 || freqHz <= 0.0 )
      return;

    // Duplicates playnote_start()'s own freq->speed formula - playnote.h
    // has no public "retune an already-playing voice" entry point of its
    // own, only a fresh play_sound()-driven start - same formula, same
    // WAVETABLE_PERIOD_SAMPLES constant, just applied to a channel that's
    // already sounding instead of starting a new one. Bypasses PlayNote's
    // own per-frame fade bookkeeping entirely (harmless: this project's
    // real PLAYNOTE_FADE_IN_FRAMES/PLAYNOTE_FADE_OUT_FRAMES are both 0, so
    // playnote_update() already skips every voice every frame - see
    // playnote.h's own fadeFramesLeft<=0 check).
    float speed = freqHz * WAVETABLE_PERIOD_SAMPLES / 44100.0;
    select_channel( channel );
    set_channel_speed( speed );
    set_channel_volume( volume );
}

void md_trackerVoiceStop( int channel )
{
    if( channel < 0 )
      return;
    playnote_stop( channel );
}

// -----------------------------------------------------------------------------
//   MEMORY CARD (backs eepromShim.h)
// -----------------------------------------------------------------------------
// Every function here is a thin wrapper around memcard.h's own real
// functions - eepromShim.c never calls card_*() directly, matching every
// other Vircon32-specific primitive in this file. Direct port of the
// sibling tinyjoypad_vircon32 project's own equivalents.

// This project's own fixed 20-word card signature - identifies "this card
// was written by gamebuino_classic_vircon32" as a whole, the same
// discipline that project's own cardSignature already uses for its own
// single-cartridge save. Distinct text from that project's own signature
// so the two are never confused if the same physical card is ever used
// with both cartridges.
game_signature cardSignature = "GAMEBUINOVIRCON01";

bool md_cardIsConnected()
{
    return card_is_connected();
}

bool md_cardHasOurSignature()
{
    return card_signature_matches( &cardSignature );
}

void md_cardWriteSignature()
{
    card_write_signature( &cardSignature );
}

void md_cardReadData( void* dest, int offsetWords, int sizeWords )
{
    card_read_data( dest, offsetWords, sizeWords );
}

void md_cardWriteData( void* src, int offsetWords, int sizeWords )
{
    card_write_data( src, offsetWords, sizeWords );
}

// -----------------------------------------------------------------------------
//   TOP-LEVEL DISPATCH: menu <-> games
// -----------------------------------------------------------------------------

int currentGameIndex = -1;
bool prevStart = false;

// -----------------------------------------------------------------------------
//   Quit-confirmation dialog (Start, while a game is running)
// -----------------------------------------------------------------------------
// Direct port of the sibling tinyjoypad_vircon32 project's own dialog - see
// that project's own CLAUDE.md for the full history of why it was added
// (Start instantly quitting risked losing real progress on an accidental
// press). While this dialog is up the current game's own update() is not
// called at all (see main()'s dispatch loop below), so gameplay is fully
// frozen rather than continuing to run behind the dialog.
bool confirmingQuit = false;
int confirmSelection = 0; // 0 = NO (default - the safer choice), 1 = YES
bool prevConfirmLeft = false;
bool prevConfirmRight = false;
bool prevConfirmA = false;

void drawConfirmQuitDialog()
{
    int boxX = 160, boxY = 110, boxW = 320, boxH = 140;
    int borderThickness = 6;

    md_drawSolidRect( boxX, boxY, boxW, boxH, color_white );
    md_drawSolidRect
    (
        boxX + borderThickness, boxY + borderThickness,
        boxW - ( borderThickness * 2 ), boxH - ( borderThickness * 2 ),
        color_black
    );

    print_at( boxX + 125, boxY + 20, "CONFIRM" );
    print_at( boxX + 95, boxY + 55, "QUIT TO MENU?" );

    int yesX = boxX + 100;
    int noX = boxX + 210;
    int optionsY = boxY + 95;

    if( confirmSelection == 1 )
      print_at( yesX - 15, optionsY, ">" );
    else
      print_at( noX - 15, optionsY, ">" );

    print_at( yesX, optionsY, "YES" );
    print_at( noX, optionsY, "NO" );
}

// -----------------------------------------------------------------------------
//   Pixel-grid overlay (Button L, while a game is running)
// -----------------------------------------------------------------------------
// Direct port of the sibling tinyjoypad_vircon32 project's own toggle - see
// that project's own CLAUDE.md ("A pixel-grid presentation overlay...") for
// the full design rationale, including a real "toggle doesn't visually take
// effect" bug found and fixed there. That specific bug doesn't reproduce
// here: unlike that project's own obonoCoreShim-lineage games (which can
// skip their own redraw indefinitely on an unchanging frame), every
// Gamebuino game here redraws through gbUpdate()/gbRenderFrame(), which
// unconditionally clears and fully repaints the whole screen on every real
// logic tick (matching real hardware's own default persistence=false
// behavior) - so a stale grid line left behind by a toggle is naturally
// repainted over within at most one game tick, with no forced onResume
// needed for correctness. The onResume call below is still wired up (and
// still gated the same way) purely for parity with the sibling project's
// own architecture, in case some future game here ever adopts a
// persistence=true-style skipped redraw.
//
// Bound to Button L rather than the sibling project's own Button X, since
// X is already spoken for here (it's real Gamebuino Button C - see
// machineDependent.h's own md_inputC()); L is otherwise unused by this
// project (Gamebuino Classic's own real hardware has no L/R shoulder
// buttons at all).
//
// Off by default and only ever toggled/rendered while a game is actually
// running (never on the menu, and not drawn on top of the quit-
// confirmation dialog either) - matching the sibling project's own
// `currentGameIndex != -1` gating exactly.
bool pixelGridEnabled = false;
bool prevGridButton = false;

// Sound on/off - Button Y (unused elsewhere: A=real Button A, B=real Button
// B, X=real Button C, L=pixel-grid toggle, Start=quit dialog), toggled
// globally rather than gated to gameplay-only the way the pixel-grid toggle
// is - matches the sibling tinyjoypad_vircon32 project's own mute toggle,
// which likewise works everywhere (menu, gameplay, dialog), not just
// mid-game. Implemented via Vircon32's own real SPU_GlobalVolume hardware
// register (set_global_volume(), range 0-2) rather than gating each
// md_playTone() call individually.
bool audioMuted = false;
bool prevMuteButton = false;

// Real-solid-gray-color toggle - Button R (unused elsewhere: A/B/X/L/Y/
// Start are all already spoken for above), flipped globally the same way
// the mute toggle is (not gated to gameplay-only), since it's a rendering
// preference rather than a gameplay feature. `gbRealGrayColor` itself
// (gamebuinoShim.h/.c) is what every drawing primitive/gbRenderFrame()
// actually reads every frame - this is just the button edge-detect that
// flips it.
bool prevGrayButton = false;

// -----------------------------------------------------------------------------
//   Toggle status badges + the transient "you just changed this" toast
// -----------------------------------------------------------------------------
//
// Three global toggles are reachable at any time - sound (Button Y), real
// solid gray (Button R) and the pixel grid (Button L, gameplay only) - and
// until now none of them showed their own state anywhere. Two things fix
// that: a permanent row of badges in the menu's own top-right corner, and a
// short-lived toast drawn over whatever is already on screen the moment any
// of the three flips, so a mid-game press is acknowledged rather than
// leaving the player guessing whether it registered.

// How long the toast stays up. The main loop runs at a real 60fps, so this
// is one second.
#define STATUS_TOAST_FRAMES 60

int statusToastFrames = 0;
int* statusToastText;

void showStatusToast( int* text )
{
    statusToastText = text;
    statusToastFrames = STATUS_TOAST_FRAMES;
}

// One badge: bright white when the toggle is on, dark gray when it is off,
// so the row reads as lit/unlit at a glance rather than having to be read.
void drawStatusBadge( int x, int y, int* label, bool enabled )
{
    if( enabled )
      set_multiply_color( color_white );
    else
      set_multiply_color( color_darkgray );

    print_at( x, y, label );
    set_multiply_color( color_white );
}

// Drawn by the menu only - during gameplay the screen belongs to the game,
// and the toast above is what reports a change instead.
void md_drawToggleStatusIcons()
{
    int y = 10;
    int gap = 2 * bios_character_width;

    // Laid out right-to-left from the screen edge so the row stays anchored
    // to the corner whatever the labels are.
    int gridX = screen_width - 12 - strlen( "GRID" ) * bios_character_width;
    int grayX = gridX - gap - strlen( "GRAY0" ) * bios_character_width;
    int sndX  = grayX - gap - strlen( "SND" ) * bios_character_width;

    // Gray is three-state, not two, so its badge names the active mode
    // rather than only lighting up: GRAY0 (off, real hardware's own
    // dither), GRAY1 (solid), GRAY2 (LCD smear). Always 5 characters, so
    // the row's own right-aligned layout does not shift as it cycles.
    int* grayLabel = "GRAY0";
    if( gbRealGrayColor )        grayLabel = "GRAY1";
    else if( gbLcdPersistence )  grayLabel = "GRAY2";

    drawStatusBadge( sndX, y, "SND", !audioMuted );
    drawStatusBadge( grayX, y, grayLabel, gbRealGrayColor || gbLcdPersistence );
    drawStatusBadge( gridX, y, "GRID", pixelGridEnabled );
}

// Drawn last of all, every frame, over the game/menu/dialog alike - see this
// section's own header comment.
void drawStatusToast()
{
    if( statusToastFrames <= 0 )
      return;

    statusToastFrames = statusToastFrames - 1;

    int textW = strlen( statusToastText ) * bios_character_width;
    int boxW = textW + 28;
    int boxH = bios_character_height + 20;
    int boxX = ( screen_width - boxW ) / 2;
    int boxY = screen_height - boxH - 14;
    int border = 4;

    md_drawSolidRect( boxX, boxY, boxW, boxH, color_white );
    md_drawSolidRect( boxX + border, boxY + border,
                      boxW - border * 2, boxH - border * 2, color_black );

    print_at( boxX + 14, boxY + 10, statusToastText );
}

void drawPixelGridOverlay()
{
    select_texture( PIXELGRID_TEXTURE_ID );
    select_region( 0 );
    draw_region_at( ORIGIN_X, ORIGIN_Y );
}

void main()
{
    select_gamepad( 0 );

    md_initVideo();
    md_initAudio();

    // Solid gray on from the start, matching the sibling SDL/Playdate
    // build's own default. Real hardware fakes its third shade with a
    // frame-alternating checkerboard dither, which this cartridge still
    // reproduces exactly whenever the toggle is off - but on a stable,
    // non-persistent modern display that dither reads as a flicker rather
    // than as gray, so the flat rendering is the better thing to open on.
    // Button R still flips it live, both ways.
    gbRealGrayColor = true;

    addGames();
    menu_init();

    while( true )
    {
        bool start = md_inputStart();
        bool justStarted = ( start && !prevStart );
        prevStart = start;

        if( confirmingQuit )
        {
            bool left = md_inputLeft();
            bool right = md_inputRight();
            bool a = md_inputA();
            bool justLeft = ( left && !prevConfirmLeft );
            bool justRight = ( right && !prevConfirmRight );
            bool justA = ( a && !prevConfirmA );
            prevConfirmLeft = left;
            prevConfirmRight = right;
            prevConfirmA = a;

            if( justLeft || justRight )
              confirmSelection = 1 - confirmSelection;

            if( justA )
            {
                // The same physical press that just confirmed this dialog
                // must not also register as a fresh press once we're back
                // in the menu (instantly launching whatever's highlighted)
                // or back in gameplay (an unwanted in-game action the
                // instant it resumes) - md_inputA() is the single shared
                // gate every gbPressed(BTN_A)/menu A-read goes through, so
                // arming it here covers both destinations.
                md_armInputAGate();
                if( confirmSelection == 1 )
                {
                    // md_stopTone() alone only clears the one-shot voice
                    // pool (gbPlayTick()/OK()/Cancel()) - the tracker
                    // engine's own per-channel state (gbTrackIsPlaying[]/
                    // gbPatternIsPlaying[]/gbNotePlaying[]/gbActiveVoice[])
                    // isn't reset by it at all, so a game quit mid-track
                    // (e.g. 101Starships' own continuous background music)
                    // would otherwise leave that state dangling - harmless
                    // once a fresh game's own gbBegin() resets it, but real,
                    // audible silence is the whole point of quitting to the
                    // menu, not "silent until the next launch happens to
                    // reset it." gbStopTrackAll() cascades down through
                    // gbStopPattern()/gbStopNoteChannel(), which also calls
                    // md_trackerVoiceStop() on every active tracker voice.
                    gbStopTrackAll();
                    md_stopTone();
                    currentGameIndex = -1;
                    menu_init();
                }
                else if( menu_getGame( currentGameIndex )->onResume != NULL )
                  menu_getGame( currentGameIndex )->onResume();
                confirmingQuit = false;
            }
            else if( justStarted )
            {
                // pressing Start again cancels, same as selecting NO
                if( menu_getGame( currentGameIndex )->onResume != NULL )
                  menu_getGame( currentGameIndex )->onResume();
                confirmingQuit = false;
            }

            drawConfirmQuitDialog();
        }
        else if( currentGameIndex != -1 && justStarted )
        {
            confirmingQuit = true;
            confirmSelection = 0;
            // Arm against whatever Left/Right/A happen to already be held
            // at this exact moment, the same reasoning as
            // md_armInputAGate() - otherwise a leftover press from
            // gameplay could immediately register as a dialog input.
            prevConfirmLeft = md_inputLeft();
            prevConfirmRight = md_inputRight();
            prevConfirmA = md_inputA();
            // Stop audio the instant the dialog opens, not only once the
            // player actually confirms - the current game's own update()
            // (and therefore gbUpdateSoundTracker()) stops running
            // entirely the moment confirmingQuit is true, so nothing will
            // restart this while the dialog is up. If the player cancels
            // instead, onResume() (if the game defines one) or that
            // game's own per-tick "restart background music if it's not
            // still playing" logic (several already-shipped games have
            // this, e.g. 101Starships) naturally picks it back up once
            // real gameplay updates resume - this isn't a pause/resume
            // mechanism, just an honest stop.
            gbStopTrackAll();
            md_stopTone();
            drawConfirmQuitDialog();
        }
        else if( currentGameIndex == -1 )
        {
            int chosen = menu_update();
            if( chosen != -1 )
            {
                currentGameIndex = chosen;
                md_armInputAGate();
                md_beginFrame();

                // Resolve/load this game's own persistent EEPROM slot
                // (looked up by its title, not by chosen/registration
                // index - see eepromShim.c) before init() runs, since a
                // game's own init() is what actually calls
                // eeprom_read_byte()/etc to load its saved high score.
                eepromSelectGame( menu_getGame( chosen )->title );

                menu_getGame( chosen )->init();
            }
        }
        else
        {
            menu_getGame( currentGameIndex )->update();
        }

        // Button L toggles the pixel-grid overlay. The overlay itself only
        // ever DRAWS over a running game (it is an LCD-area overlay - see
        // the render gate below), but the toggle is accepted everywhere,
        // exactly like the sound and gray toggles: the menu's own status
        // badges show the state, so flipping it there is a real, visible
        // action that simply takes effect once a game is launched.
        bool gridButton = ( gamepad_button_l() > 0 );
        if( gridButton && !prevGridButton )
        {
            pixelGridEnabled = !pixelGridEnabled;

            if( pixelGridEnabled ) showStatusToast( "PIXEL GRID ON" );
            else                   showStatusToast( "PIXEL GRID OFF" );

            // Only meaningful while a game is actually running.
            if( currentGameIndex != -1 )
              if( menu_getGame( currentGameIndex )->onResume != NULL )
                menu_getGame( currentGameIndex )->onResume();
        }
        prevGridButton = gridButton;

        if( currentGameIndex != -1 && !confirmingQuit && pixelGridEnabled )
          drawPixelGridOverlay();

        // Button Y toggles sound globally - unlike the pixel-grid toggle
        // above, deliberately NOT gated to "a game is running": the menu
        // itself is silent today, but gating this to gameplay-only would be
        // a surprising inconsistency, and would mean muting mid-game then
        // returning to the menu and back couldn't be done from the menu
        // screen itself.
        bool muteButton = ( gamepad_button_y() > 0 );
        if( muteButton && !prevMuteButton )
        {
            audioMuted = !audioMuted;

            if( audioMuted )
            {
                set_global_volume( 0.0 );
                showStatusToast( "SOUND OFF" );
            }
            else
            {
                set_global_volume( 1.0 );
                showStatusToast( "SOUND ON" );
            }
        }
        prevMuteButton = muteButton;

        // Button R cycles the three GB_GRAY renderings globally, everywhere,
        // exactly like the mute toggle above - see prevGrayButton's own
        // comment. Order is off -> solid -> LCD -> off; the two "on" modes
        // are mutually exclusive by construction (gbLcdPersistence needs
        // GB_GRAY to dither normally to have anything to smear), so cycling
        // one flag on always clears the other.
        bool grayButton = ( gamepad_button_r() > 0 );
        if( grayButton && !prevGrayButton )
        {
            if( gbRealGrayColor )
            {
                gbRealGrayColor = false;
                gbLcdPersistence = true;
                showStatusToast( "GRAY 2: LCD SMEAR" );
            }
            else if( gbLcdPersistence )
            {
                gbLcdPersistence = false;
                showStatusToast( "GRAY OFF: DITHER" );
            }
            else
            {
                gbRealGrayColor = true;
                showStatusToast( "GRAY 1: SOLID" );
            }
        }
        prevGrayButton = grayButton;

        // Last of all, so it lands on top of the game's own finished frame,
        // the pixel-grid overlay and the quit dialog alike.
        drawStatusToast();

        md_updateAudio();
        md_endFrame();
    }
}
