#!/usr/bin/env python3
"""Extracts the real per-track segment data (curves/hills/lane-width/signs)
from the real, genuine B-RALLY.DAT SD-card track file (staged at
more games/B-Rally/bin/B-RALLY.DAT, confirmed byte-identical to the copy
embedded in more games/Gamebuino-Classic-Games-Compilation/B-RALLY.DAT) and
prints the C data this project's own gameBRally.c embeds directly, replacing
the earlier procedural sine-curve approximation (see gameBRally.c's own
header comment for the full history of why this exists).

Real file format (matches running.ino's own levelStart()/getNextSegment()
exactly, confirmed by directly reading real B-Rally.ino):
  - one 131072-byte block per track (10 tracks total), track N starting at
    byte offset N*131072
  - each block: a 4-byte header (totalLength hi/lo, lapLength hi/lo, both
    big-endian 16-bit), then one 4-byte record per distance unit
    (x, y, lanes-1, signs)
  - x/y are real signed AVR `char` on assignment (`s.x = pf_buf[0];` with
    `char x;` in the real `segment` struct) - narrowed here explicitly to
    match (byte>=128 reinterpreted as byte-256), the same "replicate real
    AVR narrow-int behavior explicitly" precedent this project already
    applies elsewhere (see CLAUDE.md's own EEPROM-narrowing audit).

CONFIRMED DIRECTLY (not assumed) by parsing every one of the 10 real
tracks: every track's own lapLength is exactly 1000, and its own segment
data genuinely REPEATS every lapLength distance units (checked byte-for-
byte, lap 0 vs lap 1 vs lap 2 all identical) - so only the first 1000
real segments per track need to be embedded; a real lap is later replayed
by indexing (position % 1000), not stored again. totalLength (5000 or
10000, i.e. 5 or 10 real laps) is kept per-track since it's what decides
when the race actually ends. Also confirmed directly: every track's own
real data already contains a genuine signs==5 (finish-line sprite) marker
at position 999 (the very last segment of its own lap loop) - so no
synthetic "are we near the end" override is needed at all once this real
data is used directly; it recurs naturally once per lap, exactly matching
a real racing game's own start/finish banner.

Run from the project root: `python tools/extract_brally_tracks.py`
Writes the generated block directly to a scratch file for manual review/
splicing rather than editing gameBRally.c itself (that file interleaves
this data with hand-maintained code, so it isn't a pure generated-file
target the way e.g. the sibling gamebuino_classic_sdl project's own
thumbnailData.h is).
"""

DAT_PATH = "more games/B-Rally/bin/B-RALLY.DAT"
OUT_PATH = "tools/_brally_track_data.txt"

TRACK_COUNT = 10
TRACK_BLOCK_SIZE = 131072
LAP_LENGTH = 1000  # confirmed identical for all 10 real tracks


def signed_byte(b):
    return b - 256 if b >= 128 else b


def format_array(name, values, per_line=20):
    lines = []
    lines.append("int[%d] %s = {" % (len(values), name))
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("    " + ", ".join(str(v) for v in chunk) + ("," if i + per_line < len(values) else ""))
    lines.append("};")
    return "\n".join(lines)


def main():
    data = open(DAT_PATH, "rb").read()

    all_x = []
    all_y = []
    all_lanes = []
    all_signs = []
    total_lengths = []

    for track in range(TRACK_COUNT):
        base = track * TRACK_BLOCK_SIZE
        total_length = data[base] * 256 + data[base + 1]
        lap_length = data[base + 2] * 256 + data[base + 3]
        assert lap_length == LAP_LENGTH, "track %d has lapLength %d, expected %d" % (track, lap_length, LAP_LENGTH)
        total_lengths.append(total_length)

        seg_start = base + 4
        for i in range(LAP_LENGTH):
            off = seg_start + i * 4
            x, y, lanes_raw, signs = data[off], data[off + 1], data[off + 2], data[off + 3]
            all_x.append(signed_byte(x))
            all_y.append(signed_byte(y))
            all_lanes.append(lanes_raw + 1)
            all_signs.append(signs)

    with open(OUT_PATH, "w") as f:
        f.write("// GENERATED by tools/extract_brally_tracks.py from the real\n")
        f.write("// more games/B-Rally/bin/B-RALLY.DAT track file - do not hand-edit.\n")
        f.write("// Index into all four arrays below as [trackIdx*BRALLY_LAPLENGTH + (pos %% BRALLY_LAPLENGTH)].\n\n")
        f.write(format_array("brallyTrackTotalLength", total_lengths) + "\n\n")
        f.write(format_array("brallyTrackX", all_x) + "\n\n")
        f.write(format_array("brallyTrackY", all_y) + "\n\n")
        f.write(format_array("brallyTrackLanes", all_lanes) + "\n\n")
        f.write(format_array("brallyTrackSigns", all_signs) + "\n")

    print("Wrote %s (%d tracks x %d segments x 4 fields)" % (OUT_PATH, TRACK_COUNT, LAP_LENGTH))


if __name__ == "__main__":
    main()
